#!/usr/bin/perl
use strict;
use warnings;
use Cwd;

# Check for py__module.txt
if (-e "py__module.txt") {
    print "Python module marker found. Installing pip modules...\n";

    if (-e "pip.install.pymodule.txt") {
        open my $fh, '<', "pip.install.pymodule.txt" or die "Cannot open pip.install.pymodule.txt: $!";
        while (my $module = <$fh>) {
            chomp $module;
            next unless $module;  # skip empty lines
            eval {
                system("pip install $module") == 0 or die "Failed to install $module\n";
            };
            if ($@) {
                warn "Error: $@";
            }
        }
        close $fh;
    } else {
        warn "pip.install.pymodule.txt not found\n";
    }
} else {
    print "py__module.txt not found. Skipping pip install.\n";
}

# Navigate to lib directory and check for package.json
if (-d "lib") {
    chdir "lib" or die "Failed to change to lib directory: $!";
    if (-e "package.json") {
        print "package.json found in lib/. Running npm install...\n";
        system("npm install") == 0 or warn "npm install failed.\n";
    } else {
        print "package.json not found in lib/. Skipping npm install.\n";
    }
} else {
    print "lib directory not found. Skipping npm install.\n";
}
